const caseDatabase = [
  { name: "NZXT H7 Flow RGB Black", type: "Mid Tower", motherboard: "ATX / Micro-ATX", maxGpuLength: "400 mm", maxCpuCooler: "185 mm", fanSupport: "3x 140mm", color: "Black", image: "assets/NZXT.png" },
  { name: "NZXT H7 Flow RGB White", type: "Mid Tower", motherboard: "ATX / Micro-ATX", maxGpuLength: "400 mm", maxCpuCooler: "185 mm", fanSupport: "3x 140mm", color: "White", image: "assets/NZXT.png" },
  { name: "NZXT H6 Flow RGB Black", type: "Mid Tower", motherboard: "ATX / Micro-ATX", maxGpuLength: "365 mm", maxCpuCooler: "163 mm", fanSupport: "3x 120mm", color: "Black", image: "assets/NZXT.png" },
  { name: "NZXT H6 Flow RGB White", type: "Mid Tower", motherboard: "ATX / Micro-ATX", maxGpuLength: "365 mm", maxCpuCooler: "163 mm", fanSupport: "3x 120mm", color: "White", image: "assets/NZXT.png" },
  { name: "NZXT H9 Flow Black", type: "Mid Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "435 mm", maxCpuCooler: "165 mm", fanSupport: "10x 120mm", color: "Black", image: "assets/NZXT.png" },
  { name: "NZXT H9 Flow White", type: "Mid Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "435 mm", maxCpuCooler: "165 mm", fanSupport: "10x 120mm", color: "White", image: "assets/NZXT.png" },
  { name: "NZXT H9 Elite Black", type: "Mid Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "435 mm", maxCpuCooler: "165 mm", fanSupport: "10x 120mm", color: "Black", image: "assets/NZXT.png" },
  { name: "NZXT H9 Elite White", type: "Mid Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "435 mm", maxCpuCooler: "165 mm", fanSupport: "10x 120mm", color: "White", image: "assets/NZXT.png" },
  { name: "NZXT H5 Flow Black", type: "Mid Tower", motherboard: "ATX / Micro-ATX", maxGpuLength: "365 mm", maxCpuCooler: "165 mm", fanSupport: "6x 120mm", color: "Black", image: "assets/NZXT.png" },
  { name: "NZXT H5 Flow White", type: "Mid Tower", motherboard: "ATX / Micro-ATX", maxGpuLength: "365 mm", maxCpuCooler: "165 mm", fanSupport: "6x 120mm", color: "White", image: "assets/NZXT.png" },
  { name: "NZXT H5 Elite Black", type: "Mid Tower", motherboard: "ATX / Micro-ATX", maxGpuLength: "365 mm", maxCpuCooler: "165 mm", fanSupport: "6x 120mm", color: "Black", image: "assets/NZXT.png" },
  { name: "NZXT H5 Elite White", type: "Mid Tower", motherboard: "ATX / Micro-ATX", maxGpuLength: "365 mm", maxCpuCooler: "165 mm", fanSupport: "6x 120mm", color: "White", image: "assets/NZXT.png" },
  { name: "NZXT H210 Black", type: "Mini-ITX", motherboard: "Mini-ITX", maxGpuLength: "325 mm", maxCpuCooler: "165 mm", fanSupport: "4x 120mm", color: "Black", image: "assets/NZXT.png" },
  { name: "NZXT H210 White", type: "Mini-ITX", motherboard: "Mini-ITX", maxGpuLength: "325 mm", maxCpuCooler: "165 mm", fanSupport: "4x 120mm", color: "White", image: "assets/NZXT.png" },

  { name: "Corsair 4000D Airflow Black", type: "Mid Tower", motherboard: "ATX / Micro-ATX", maxGpuLength: "360 mm", maxCpuCooler: "170 mm", fanSupport: "6x 120mm", color: "Black", image: "assets/Corsair.png" },
  { name: "Corsair 4000D Airflow White", type: "Mid Tower", motherboard: "ATX / Micro-ATX", maxGpuLength: "360 mm", maxCpuCooler: "170 mm", fanSupport: "6x 120mm", color: "White", image: "assets/Corsair.png" },
  { name: "Corsair 5000D Airflow Black", type: "Mid Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "420 mm", maxCpuCooler: "170 mm", fanSupport: "10x 120mm", color: "Black", image: "assets/Corsair.png" },
  { name: "Corsair 5000D Airflow White", type: "Mid Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "420 mm", maxCpuCooler: "170 mm", fanSupport: "10x 120mm", color: "White", image: "assets/Corsair.png" },
  { name: "Corsair 6500D Airflow Black", type: "Dual Chamber", motherboard: "ATX / Micro-ATX", maxGpuLength: "400 mm", maxCpuCooler: "170 mm", fanSupport: "13x 120mm", color: "Black", image: "assets/Corsair.png" },
  { name: "Corsair 6500D Airflow White", type: "Dual Chamber", motherboard: "ATX / Micro-ATX", maxGpuLength: "400 mm", maxCpuCooler: "170 mm", fanSupport: "13x 120mm", color: "White", image: "assets/Corsair.png" },
  { name: "Corsair 6500X RGB Black", type: "Dual Chamber", motherboard: "ATX / Micro-ATX", maxGpuLength: "400 mm", maxCpuCooler: "170 mm", fanSupport: "13x 120mm", color: "Black", image: "assets/Corsair.png" },
  { name: "Corsair 6500X RGB White", type: "Dual Chamber", motherboard: "ATX / Micro-ATX", maxGpuLength: "400 mm", maxCpuCooler: "170 mm", fanSupport: "13x 120mm", color: "White", image: "assets/Corsair.png" },
  { name: "Corsair 7000D Airflow Black", type: "Full Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "450 mm", maxCpuCooler: "190 mm", fanSupport: "12x 120mm", color: "Black", image: "assets/Corsair.png" },
  { name: "Corsair 7000D Airflow White", type: "Full Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "450 mm", maxCpuCooler: "190 mm", fanSupport: "12x 120mm", color: "White", image: "assets/Corsair.png" },
  { name: "Corsair iCUE 220T RGB Airflow Black", type: "Mid Tower", motherboard: "ATX / Micro-ATX", maxGpuLength: "300 mm", maxCpuCooler: "160 mm", fanSupport: "6x 120mm", color: "Black", image: "assets/Corsair.png" },
  { name: "Corsair iCUE 220T RGB Airflow White", type: "Mid Tower", motherboard: "ATX / Micro-ATX", maxGpuLength: "300 mm", maxCpuCooler: "160 mm", fanSupport: "6x 120mm", color: "White", image: "assets/Corsair.png" },
  { name: "Corsair 3000D Airflow Black", type: "Mid Tower", motherboard: "ATX / Micro-ATX", maxGpuLength: "360 mm", maxCpuCooler: "170 mm", fanSupport: "6x 120mm", color: "Black", image: "assets/Corsair.png" },
  { name: "Corsair 3000D Airflow White", type: "Mid Tower", motherboard: "ATX / Micro-ATX", maxGpuLength: "360 mm", maxCpuCooler: "170 mm", fanSupport: "6x 120mm", color: "White", image: "assets/Corsair.png" },

  { name: "Lian Li O11 Dynamic EVO Black", type: "Mid Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "422 mm", maxCpuCooler: "167 mm", fanSupport: "10x 120mm", color: "Black", image: "assets/Lian Li.png" },
  { name: "Lian Li O11 Dynamic EVO White", type: "Mid Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "422 mm", maxCpuCooler: "167 mm", fanSupport: "10x 120mm", color: "White", image: "assets/Lian Li.png" },
  { name: "Lian Li O11 Dynamic EVO RGB Black", type: "Mid Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "455 mm", maxCpuCooler: "167 mm", fanSupport: "10x 120mm", color: "Black", image: "assets/Lian Li.png" },
  { name: "Lian Li O11 Dynamic EVO RGB White", type: "Mid Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "455 mm", maxCpuCooler: "167 mm", fanSupport: "10x 120mm", color: "White", image: "assets/Lian Li.png" },
  { name: "Lian Li O11 Vision Black", type: "Mid Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "455 mm", maxCpuCooler: "167 mm", fanSupport: "8x 120mm", color: "Black", image: "assets/Lian Li.png" },
  { name: "Lian Li O11 Vision White", type: "Mid Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "455 mm", maxCpuCooler: "167 mm", fanSupport: "8x 120mm", color: "White", image: "assets/Lian Li.png" },
  { name: "Lian Li Lancool 216 Black", type: "Mid Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "392 mm", maxCpuCooler: "180 mm", fanSupport: "9x 120mm", color: "Black", image: "assets/Lian Li.png" },
  { name: "Lian Li Lancool 216 White", type: "Mid Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "392 mm", maxCpuCooler: "180 mm", fanSupport: "9x 120mm", color: "White", image: "assets/Lian Li.png" },
  { name: "Lian Li Lancool III Black", type: "Mid Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "435 mm", maxCpuCooler: "187 mm", fanSupport: "10x 120mm", color: "Black", image: "assets/Lian Li.png" },
  { name: "Lian Li Lancool III White", type: "Mid Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "435 mm", maxCpuCooler: "187 mm", fanSupport: "10x 120mm", color: "White", image: "assets/Lian Li.png" },
  { name: "Lian Li A3-mATX Black", type: "Mini Tower", motherboard: "Micro-ATX / Mini-ITX", maxGpuLength: "415 mm", maxCpuCooler: "165 mm", fanSupport: "10x 120mm", color: "Black", image: "assets/Lian Li.png" },
  { name: "Lian Li A3-mATX White", type: "Mini Tower", motherboard: "Micro-ATX / Mini-ITX", maxGpuLength: "415 mm", maxCpuCooler: "165 mm", fanSupport: "10x 120mm", color: "White", image: "assets/Lian Li.png" },

  { name: "Phanteks Eclipse G360A Black", type: "Mid Tower", motherboard: "ATX / Micro-ATX", maxGpuLength: "400 mm", maxCpuCooler: "160 mm", fanSupport: "7x 120mm", color: "Black", image: "assets/Phanteks.png" },
  { name: "Phanteks Eclipse G360A White", type: "Mid Tower", motherboard: "ATX / Micro-ATX", maxGpuLength: "400 mm", maxCpuCooler: "160 mm", fanSupport: "7x 120mm", color: "White", image: "assets/Phanteks.png" },
  { name: "Phanteks Eclipse G400A Black", type: "Mid Tower", motherboard: "ATX / Micro-ATX", maxGpuLength: "420 mm", maxCpuCooler: "160 mm", fanSupport: "6x 120mm", color: "Black", image: "assets/Phanteks.png" },
  { name: "Phanteks NV5 Black", type: "Mid Tower", motherboard: "ATX / Micro-ATX", maxGpuLength: "440 mm", maxCpuCooler: "180 mm", fanSupport: "8x 120mm", color: "Black", image: "assets/Phanteks.png" },
  { name: "Phanteks NV5 White", type: "Mid Tower", motherboard: "ATX / Micro-ATX", maxGpuLength: "440 mm", maxCpuCooler: "180 mm", fanSupport: "8x 120mm", color: "White", image: "assets/Phanteks.png" },
  { name: "Phanteks NV7 Black", type: "Full Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "450 mm", maxCpuCooler: "185 mm", fanSupport: "12x 120mm", color: "Black", image: "assets/Phanteks.png" },
  { name: "Phanteks NV7 White", type: "Full Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "450 mm", maxCpuCooler: "185 mm", fanSupport: "12x 120mm", color: "White", image: "assets/Phanteks.png" },
  { name: "Phanteks NV9 Black", type: "Full Tower", motherboard: "EEB / E-ATX / ATX", maxGpuLength: "490 mm", maxCpuCooler: "205 mm", fanSupport: "13x 140mm", color: "Black", image: "assets/Phanteks.png" },
  { name: "Phanteks NV9 White", type: "Full Tower", motherboard: "EEB / E-ATX / ATX", maxGpuLength: "490 mm", maxCpuCooler: "205 mm", fanSupport: "13x 140mm", color: "White", image: "assets/Phanteks.png" },
  { name: "Phanteks Enthoo Pro 2 Black", type: "Full Tower", motherboard: "EEB / E-ATX / ATX", maxGpuLength: "503 mm", maxCpuCooler: "195 mm", fanSupport: "15x 120mm", color: "Black", image: "assets/Phanteks.png" },

  { name: "Cooler Master MasterBox TD500 Mesh V2 Black", type: "Mid Tower", motherboard: "ATX / Micro-ATX", maxGpuLength: "410 mm", maxCpuCooler: "165 mm", fanSupport: "7x 120mm", color: "Black", image: "assets/Cooler Master.png" },
  { name: "Cooler Master MasterBox TD500 Mesh V2 White", type: "Mid Tower", motherboard: "ATX / Micro-ATX", maxGpuLength: "410 mm", maxCpuCooler: "165 mm", fanSupport: "7x 120mm", color: "White", image: "assets/Cooler Master.png" },
  { name: "Cooler Master MasterBox Q300L Black", type: "Mini Tower", motherboard: "Micro-ATX / Mini-ITX", maxGpuLength: "360 mm", maxCpuCooler: "157 mm", fanSupport: "6x 120mm", color: "Black", image: "assets/Cooler Master.png" },
  { name: "Cooler Master MasterBox Q300L V2", type: "Mini Tower", motherboard: "Micro-ATX / Mini-ITX", maxGpuLength: "360 mm", maxCpuCooler: "157 mm", fanSupport: "6x 120mm", color: "Black", image: "assets/Cooler Master.png" },
  { name: "Cooler Master HAF 700 Berserker", type: "Full Tower", motherboard: "EEB / E-ATX / ATX", maxGpuLength: "490 mm", maxCpuCooler: "166 mm", fanSupport: "18x 120mm", color: "Black", image: "assets/Cooler Master.png" },
  { name: "Cooler Master HAF 500 Black", type: "Mid Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "410 mm", maxCpuCooler: "167 mm", fanSupport: "8x 120mm", color: "Black", image: "assets/Cooler Master.png" },
  { name: "Cooler Master HAF 500 White", type: "Mid Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "410 mm", maxCpuCooler: "167 mm", fanSupport: "8x 120mm", color: "White", image: "assets/Cooler Master.png" },
  { name: "Cooler Master MasterBox MB511 RGB", type: "Mid Tower", motherboard: "ATX / Micro-ATX", maxGpuLength: "410 mm", maxCpuCooler: "165 mm", fanSupport: "6x 120mm", color: "Black", image: "assets/Cooler Master.png" },
  { name: "Cooler Master MasterBox MB311L ARGB", type: "Mini Tower", motherboard: "Micro-ATX / Mini-ITX", maxGpuLength: "344 mm", maxCpuCooler: "166 mm", fanSupport: "6x 120mm", color: "Black", image: "assets/Cooler Master.png" },
  { name: "Cooler Master Cosmos C700M", type: "Full Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "490 mm", maxCpuCooler: "198 mm", fanSupport: "9x 120mm", color: "Silver / Black", image: "assets/Cooler Master.png" },

  { name: "Fractal Design North Black", type: "Mid Tower", motherboard: "ATX / Micro-ATX", maxGpuLength: "355 mm", maxCpuCooler: "170 mm", fanSupport: "6x 120mm", color: "Black", image: "assets/Fractal Design.png" },
  { name: "Fractal Design North White", type: "Mid Tower", motherboard: "ATX / Micro-ATX", maxGpuLength: "355 mm", maxCpuCooler: "170 mm", fanSupport: "6x 120mm", color: "White", image: "assets/Fractal Design.png" },
  { name: "Fractal Design North XL Black", type: "Full Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "413 mm", maxCpuCooler: "185 mm", fanSupport: "9x 120mm", color: "Black", image: "assets/Fractal Design.png" },
  { name: "Fractal Design North XL White", type: "Full Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "413 mm", maxCpuCooler: "185 mm", fanSupport: "9x 120mm", color: "White", image: "assets/Fractal Design.png" },
  { name: "Fractal Design Meshify 2 Compact Black", type: "Mid Tower", motherboard: "ATX / Micro-ATX", maxGpuLength: "360 mm", maxCpuCooler: "169 mm", fanSupport: "7x 120mm", color: "Black", image: "assets/Fractal Design.png" },
  { name: "Fractal Design Meshify 2 Compact White", type: "Mid Tower", motherboard: "ATX / Micro-ATX", maxGpuLength: "360 mm", maxCpuCooler: "169 mm", fanSupport: "7x 120mm", color: "White", image: "assets/Fractal Design.png" },
  { name: "Fractal Design Torrent Black", type: "Mid Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "461 mm", maxCpuCooler: "188 mm", fanSupport: "9x 120mm", color: "Black", image: "assets/Fractal Design.png" },
  { name: "Fractal Design Torrent White", type: "Mid Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "461 mm", maxCpuCooler: "188 mm", fanSupport: "9x 120mm", color: "White", image: "assets/Fractal Design.png" },
  { name: "Fractal Design Pop Air Black", type: "Mid Tower", motherboard: "ATX / Micro-ATX", maxGpuLength: "405 mm", maxCpuCooler: "170 mm", fanSupport: "5x 120mm", color: "Black", image: "assets/Fractal Design.png" },
  { name: "Fractal Design Pop Air White", type: "Mid Tower", motherboard: "ATX / Micro-ATX", maxGpuLength: "405 mm", maxCpuCooler: "170 mm", fanSupport: "5x 120mm", color: "White", image: "assets/Fractal Design.png" },

  { name: "be quiet! Shadow Base 800 FX Black", type: "Full Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "430 mm", maxCpuCooler: "180 mm", fanSupport: "8x 120mm", color: "Black", image: "assets/be quiet!.png" },
  { name: "be quiet! Shadow Base 800 FX White", type: "Full Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "430 mm", maxCpuCooler: "180 mm", fanSupport: "8x 120mm", color: "White", image: "assets/be quiet!.png" },
  { name: "be quiet! Silent Base 802 Black", type: "Full Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "432 mm", maxCpuCooler: "185 mm", fanSupport: "7x 120mm", color: "Black", image: "assets/be quiet!.png" },
  { name: "be quiet! Silent Base 802 White", type: "Full Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "432 mm", maxCpuCooler: "185 mm", fanSupport: "7x 120mm", color: "White", image: "assets/be quiet!.png" },
  { name: "be quiet! Pure Base 500DX Black", type: "Mid Tower", motherboard: "ATX / Micro-ATX", maxGpuLength: "369 mm", maxCpuCooler: "190 mm", fanSupport: "6x 120mm", color: "Black", image: "assets/be quiet!.png" },
  { name: "be quiet! Pure Base 500DX White", type: "Mid Tower", motherboard: "ATX / Micro-ATX", maxGpuLength: "369 mm", maxCpuCooler: "190 mm", fanSupport: "6x 120mm", color: "White", image: "assets/be quiet!.png" },
  { name: "be quiet! Dark Base Pro 901", type: "Full Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "495 mm", maxCpuCooler: "190 mm", fanSupport: "10x 120mm", color: "Black", image: "assets/be quiet!.png" },

  { name: "Thermaltake Core P3 TG Pro Black", type: "Open Frame", motherboard: "ATX / Micro-ATX", maxGpuLength: "450 mm", maxCpuCooler: "180 mm", fanSupport: "4x 120mm", color: "Black", image: "assets/Thermaltake.png" },
  { name: "Thermaltake Core P3 TG Pro Snow", type: "Open Frame", motherboard: "ATX / Micro-ATX", maxGpuLength: "450 mm", maxCpuCooler: "180 mm", fanSupport: "4x 120mm", color: "White", image: "assets/Thermaltake.png" },
  { name: "Thermaltake The Tower 300 Black", type: "Vertical Tower", motherboard: "Micro-ATX / Mini-ITX", maxGpuLength: "400 mm", maxCpuCooler: "210 mm", fanSupport: "8x 120mm", color: "Black", image: "assets/Thermaltake.png" },
  { name: "Thermaltake The Tower 300 Hydrangea Blue", type: "Vertical Tower", motherboard: "Micro-ATX / Mini-ITX", maxGpuLength: "400 mm", maxCpuCooler: "210 mm", fanSupport: "8x 120mm", color: "Blue", image: "assets/Thermaltake.png" },
  { name: "Thermaltake The Tower 500 Black", type: "Vertical Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "325 mm", maxCpuCooler: "275 mm", fanSupport: "8x 120mm", color: "Black", image: "assets/Thermaltake.png" },
  { name: "Thermaltake View 300 MX Black", type: "Mid Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "400 mm", maxCpuCooler: "175 mm", fanSupport: "9x 120mm", color: "Black", image: "assets/Thermaltake.png" },
  { name: "Thermaltake View 300 MX Snow", type: "Mid Tower", motherboard: "E-ATX / ATX / Micro-ATX", maxGpuLength: "400 mm", maxCpuCooler: "175 mm", fanSupport: "9x 120mm", color: "White", image: "assets/Thermaltake.png" }
];

// สั่งแสดงผลการ์ดสินค้าบนหน้าจอเมื่อโหลดไฟล์เสร็จ
if (typeof checkCaseSearchParam === 'function') {
  checkCaseSearchParam();
}