// gpu-data.js
const gpuDatabase = [
    {
        name: "Palit GeForce RTX 3050 Dual",
        brand: "Palit",
        model: "GeForce RTX 3050",
        memorySize: "6 GB GDDR6",
        maxResolution: "7680 x 4320",
        hdmiPort: "1 x HDMI 2.1",
        powerRequirement: "300 Watt",
        dimension: "162 x 117 x 40 mm",
        warranty: "3 Years",
        image: "https://www.palit.com/product/vga/picture/p04468/p04468_propng_996397d7ff0c4a9.png"
    },
    {
        name: "NVIDIA GeForce RTX 4080 Founders Edition",
        brand: "NVIDIA",
        model: "GeForce RTX 4080",
        memorySize: "16 GB GDDR6X",
        maxResolution: "7680 x 4320",
        hdmiPort: "1 x HDMI 2.1",
        powerRequirement: "320 Watt",
        dimension: "304 x 137 x 61 mm",
        warranty: "3 Years",
        image: "assets/RTX 4080.png"
    },
    {
        name: "AMD Radeon RX 7900 XTX",
        brand: "AMD",
        model: "Radeon RX 7900 XTX",
        memorySize: "24 GB GDDR6",
        maxResolution: "7680 x 4320",
        hdmiPort: "1 x HDMI 2.1",
        powerRequirement: "420 Watt",
        dimension: "318 x 137 x 54 mm",
        warranty: "3 Years",
        image: "assets/RX 7900.png"
    },
    {
        name: "Palit GeForce RTX 4060 Dual",
        brand: "Palit",
        model: "GeForce RTX 4060",
        memorySize: "8 GB GDDR6",
        maxResolution: "7680 x 4320",
        hdmiPort: "1 x HDMI 2.1a",
        powerRequirement: "600 Watt",
        dimension: "249.9 x 123.5 x 40.2 mm",
        warranty: "3 Years",
        image: "assets/RTX 4060.png"
    },
    {
        name: "Galax GeForce RTX 4060 Ti 8GB Click OC",
        brand: "Galax",
        model: "GeForce RTX 4060 Ti",
        memorySize: "8 GB GDDR6",
        maxResolution: "7680 x 4320",
        hdmiPort: "1 x HDMI 2.1a",
        powerRequirement: "550 Watt",
        dimension: "251 x 133 x 41 mm",
        warranty: "3 Years",
        image: "assets/GALAX.png"
    },
    {
        name: "NVIDIA GeForce RTX 4090 Founders Edition",
        brand: "NVIDIA",
        model: "GeForce RTX 4090",
        memorySize: "24 GB GDDR6X",
        maxResolution: "7680 x 4320",
        hdmiPort: "1 x HDMI 2.1a",
        powerRequirement: "850 Watt",
        dimension: "304 x 137 x 61 mm",
        warranty: "3 Years",
        image: "assets/NVIDIA.png"
    },
    {
        name: "Palit GeForce RTX 4070 Super Dual",
        brand: "Palit",
        model: "GeForce RTX 4070 Super",
        memorySize: "12 GB GDDR6X",
        maxResolution: "7680 x 4320",
        hdmiPort: "1 x HDMI 2.1a",
        powerRequirement: "750 Watt",
        dimension: "269.1 x 127.5 x 40.1 mm",
        warranty: "3 Years",
        image: "assets/RALIT.png"
    },
    {
        name: "AMD Radeon RX 7800 XT",
        brand: "AMD",
        model: "Radeon RX 7800 XT",
        memorySize: "16 GB GDDR6",
        maxResolution: "7680 x 4320",
        hdmiPort: "1 x HDMI 2.1",
        powerRequirement: "700 Watt",
        dimension: "267 x 111 x 50 mm",
        warranty: "3 Years",
        image: "assets/AMD.png"
    },
    {
        name: "NVIDIA GeForce RTX 4070 Ti Super",
        brand: "NVIDIA",
        model: "GeForce RTX 4070 Ti Super",
        memorySize: "16 GB GDDR6X",
        maxResolution: "7680 x 4320",
        hdmiPort: "1 x HDMI 2.1a",
        powerRequirement: "700 Watt",
        dimension: "285 x 112 x 42 mm",
        warranty: "3 Years",
        image: "assets/NVIDIA.png"
    },
    {
        name: "AMD Radeon RX 7600 XT",
        brand: "AMD",
        model: "Radeon RX 7600 XT",
        memorySize: "16 GB GDDR6",
        maxResolution: "7680 x 4320",
        hdmiPort: "1 x HDMI 2.1",
        powerRequirement: "600 Watt",
        dimension: "241 x 111 x 50 mm",
        warranty: "3 Years",
        image: "assets/AMD.png"
    },
    {
        name: "NVIDIA GeForce RTX 3060 Ti",
        brand: "NVIDIA",
        model: "GeForce RTX 3060 Ti",
        memorySize: "8 GB GDDR6",
        maxResolution: "7680 x 4320",
        hdmiPort: "1 x HDMI 2.1",
        powerRequirement: "600 Watt",
        dimension: "242 x 112 x 38 mm",
        warranty: "3 Years",
        image: "assets/NVIDIA.png"
    },
    {
        name: "Palit GeForce RTX 3060 Dual",
        brand: "Palit",
        model: "GeForce RTX 3060",
        memorySize: "12 GB GDDR6",
        maxResolution: "7680 x 4320",
        hdmiPort: "1 x HDMI 2.1",
        powerRequirement: "550 Watt",
        dimension: "245 x 119 x 40 mm",
        warranty: "3 Years",
        image: "assets/RALIT.png"
    },
    {
        name: "AMD Radeon RX 6700 XT",
        brand: "AMD",
        model: "Radeon RX 6700 XT",
        memorySize: "12 GB GDDR6",
        maxResolution: "7680 x 4320",
        hdmiPort: "1 x HDMI 2.1",
        powerRequirement: "650 Watt",
        dimension: "267 x 110 x 40 mm",
        warranty: "3 Years",
        image: "assets/AMD.png"
    },
    {
        name: "NVIDIA GeForce RTX 3070 Founders Edition",
        brand: "NVIDIA",
        model: "GeForce RTX 3070",
        memorySize: "8 GB GDDR6",
        maxResolution: "7680 x 4320",
        hdmiPort: "1 x HDMI 2.1",
        powerRequirement: "650 Watt",
        dimension: "242 x 112 x 40 mm",
        warranty: "3 Years",
        image: "assets/NVIDIA.png"
    },
    {
        name: "Palit GeForce RTX 3070 Ti GamingPro",
        brand: "Palit",
        model: "GeForce RTX 3070 Ti",
        memorySize: "8 GB GDDR6X",
        maxResolution: "7680 x 4320",
        hdmiPort: "1 x HDMI 2.1",
        powerRequirement: "700 Watt",
        dimension: "294 x 112 x 60 mm",
        warranty: "3 Years",
        image: "assets/RALIT.png"
    },
    {
        name: "AMD Radeon RX 7700 XT",
        brand: "AMD",
        model: "Radeon RX 7700 XT",
        memorySize: "12 GB GDDR6",
        maxResolution: "7680 x 4320",
        hdmiPort: "1 x HDMI 2.1",
        powerRequirement: "700 Watt",
        dimension: "267 x 110 x 50 mm",
        warranty: "3 Years",
        image: "assets/AMD.png"
    },
    {
        name: "NVIDIA GeForce RTX 3080 Founders Edition",
        brand: "NVIDIA",
        model: "GeForce RTX 3080",
        memorySize: "10 GB GDDR6X",
        maxResolution: "7680 x 4320",
        hdmiPort: "1 x HDMI 2.1",
        powerRequirement: "750 Watt",
        dimension: "285 x 112 x 40 mm",
        warranty: "3 Years",
        image: "assets/NVIDIA.png"
    },
    {
        name: "AMD Radeon RX 6950 XT",
        brand: "AMD",
        model: "Radeon RX 6950 XT",
        memorySize: "16 GB GDDR6",
        maxResolution: "7680 x 4320",
        hdmiPort: "1 x HDMI 2.1",
        powerRequirement: "850 Watt",
        dimension: "267 x 120 x 50 mm",
        warranty: "3 Years",
        image: "assets/AMD.png"
    },
    {
        name: "Galax GeForce GTX 1660 Super 1-Click OC",
        brand: "Galax",
        model: "GeForce GTX 1660 Super",
        memorySize: "6 GB GDDR6",
        maxResolution: "7680 x 4320",
        hdmiPort: "1 x HDMI 2.0b",
        powerRequirement: "450 Watt",
        dimension: "228 x 131.5 x 41.5 mm",
        warranty: "3 Years",
        image: "assets/GALAX.png"
    },
    {
        name: "Palit GeForce GTX 1650 StormX",
        brand: "Palit",
        model: "GeForce GTX 1650",
        memorySize: "4 GB GDDR5",
        maxResolution: "7680 x 4320",
        hdmiPort: "1 x HDMI 2.0b",
        powerRequirement: "300 Watt",
        dimension: "145 x 99 x 40 mm",
        warranty: "3 Years",
        image: "assets/RALIT.png"
    },
    {
        name: "AMD Radeon RX 6600 XT",
        brand: "AMD",
        model: "Radeon RX 6600 XT",
        memorySize: "8 GB GDDR6",
        maxResolution: "7680 x 4320",
        hdmiPort: "1 x HDMI 2.1",
        powerRequirement: "500 Watt",
        dimension: "243 x 134 x 49 mm",
        warranty: "3 Years",
        image: "assets/AMD.png"
    },
    {
        name: "NVIDIA GeForce RTX 2060 Super",
        brand: "NVIDIA",
        model: "GeForce RTX 2060 Super",
        memorySize: "8 GB GDDR6",
        maxResolution: "7680 x 4320",
        hdmiPort: "1 x HDMI 2.0b",
        powerRequirement: "550 Watt",
        dimension: "228 x 112 x 40 mm",
        warranty: "3 Years",
        image: "assets/NVIDIA.png"
    },
    {
        name: "AMD Radeon RX 7900 XT",
        brand: "AMD",
        model: "Radeon RX 7900 XT",
        memorySize: "20 GB GDDR6",
        maxResolution: "7680 x 4320",
        hdmiPort: "1 x HDMI 2.1",
        powerRequirement: "750 Watt",
        dimension: "276 x 113 x 51 mm",
        warranty: "3 Years",
        image: "assets/AMD.png"
    },
    {
        name: "Palit GeForce RTX 4070 Ti GamingPro",
        brand: "Palit",
        model: "GeForce RTX 4070 Ti",
        memorySize: "12 GB GDDR6X",
        maxResolution: "7680 x 4320",
        hdmiPort: "1 x HDMI 2.1a",
        powerRequirement: "750 Watt",
        dimension: "328.9 x 132.9 x 63.4 mm",
        warranty: "3 Years",
        image: "assets/RALIT.png"
    },
    {
        name: "NVIDIA GeForce RTX 3090 Ti Founders Edition",
        brand: "NVIDIA",
        model: "GeForce RTX 3090 Ti",
        memorySize: "24 GB GDDR6X",
        maxResolution: "7680 x 4320",
        hdmiPort: "1 x HDMI 2.1",
        powerRequirement: "850 Watt",
        dimension: "313 x 138 x 61 mm",
        warranty: "3 Years",
        image: "assets/NVIDIA.png"
    },
    {
        name: "Galax GeForce RTX 4070 EX Gamer",
        brand: "Galax",
        model: "GeForce RTX 4070",
        memorySize: "12 GB GDDR6X",
        maxResolution: "7680 x 4320",
        hdmiPort: "1 x HDMI 2.1a",
        powerRequirement: "600 Watt",
        dimension: "323 x 131 x 48 mm",
        warranty: "3 Years",
        image: "assets/GALAX.png"
    },
    {
        name: "AMD Radeon RX 6800 XT",
        brand: "AMD",
        model: "Radeon RX 6800 XT",
        memorySize: "16 GB GDDR6",
        maxResolution: "7680 x 4320",
        hdmiPort: "1 x HDMI 2.1",
        powerRequirement: "750 Watt",
        dimension: "267 x 120 x 50 mm",
        warranty: "3 Years",
        image: "assets/AMD.png"
    },
    {
        name: "Palit GeForce RTX 4080 Super GamingPro",
        brand: "Palit",
        model: "GeForce RTX 4080 Super",
        memorySize: "16 GB GDDR6X",
        maxResolution: "7680 x 4320",
        hdmiPort: "1 x HDMI 2.1a",
        powerRequirement: "850 Watt",
        dimension: "328.9 x 132.9 x 63.4 mm",
        warranty: "3 Years",
        image: "assets/RALIT.png"
    },
    {
        name: "NVIDIA GeForce RTX 2080 Ti",
        brand: "NVIDIA",
        model: "GeForce RTX 2080 Ti",
        memorySize: "11 GB GDDR6",
        maxResolution: "7680 x 4320",
        hdmiPort: "1 x HDMI 2.0b",
        powerRequirement: "650 Watt",
        dimension: "267 x 116 x 40 mm",
        warranty: "3 Years",
        image: "assets/NVIDIA.png"
    },
    {
        name: "AMD Radeon RX 6500 XT",
        brand: "AMD",
        model: "Radeon RX 6500 XT",
        memorySize: "4 GB GDDR6",
        maxResolution: "7680 x 4320",
        hdmiPort: "1 x HDMI 2.1",
        powerRequirement: "400 Watt",
        dimension: "192 x 117 x 38 mm",
        warranty: "3 Years",
        image: "assets/AMD.png"
    }
];